### ISSUE TITLE
User Auth and styling

### ISSUE THREAD

**Issue by Iulia-H** [Iulia-H/Twinkle#2]
# User Auth

## Functionality

- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

## Comments
- For now the log in button redirects back to the home page as the picture page has not been created yet.

**Comment by jenvomo** [comment]
### Comments
- [ ] Update font on splash page to a modern font
- Can't test most functionality because I am stuck in the signed in state with no logout button.  let me know when you've added that so I can check out the rest of the functionality!
